CSW( CSW_UNKNOWN, NULL, 0 ),

CSW( CSW_BLASTER,       "Blaster",         BLASTER_DMG ),
CSW( CSW_MACHINEGUN,    "Rifle",           RIFLE_DMG ),
CSW( CSW_PAINSAW,       "Pain Saw",        PAINSAW_DAMAGE ),
CSW( CSW_PAINSAW_ALT,   "Pain Saw Blade",  PAINSAW_DAMAGE2 ),
CSW( CSW_SHOTGUN,       "Shotgun",         SHOTGUN_DMG * SHOTGUN_PELLETS ),
CSW( CSW_LASGUN,        "Las Gun",         LASGUN_DAMAGE ),
CSW( CSW_MDRIVER,       "Mass Driver",     MDRIVER_DMG ),
CSW( CSW_CHAINGUN,      "Chaingun",        CHAINGUN_DMG ),
CSW( CSW_PRIFLE,        "Pulse Rifle",     PRIFLE_DMG ),
CSW( CSW_FLAMER,        "Flame Thrower",   FLAMER_DMG ),
CSW( CSW_LIGHTNING,     "Lightning Gun",   LIGHTNING_DAMAGE ),
CSW( CSW_LCANNON,       "Lucifer Cannon",  LCANNON_DAMAGE ),
CSW( CSW_LCANNON_ALT,   "Lucifer Alt.",    LCANNON_SECONDARY_DAMAGE ),
CSW( CSW_ROCKETL,       "Rocket Launcher", ROCKETL_DAMAGE ),
CSW( CSW_GRENADE,       "Grenade",         GRENADE_DAMAGE ),

CSW( CSW_ABUILDER,      "Granger",         ABUILDER_CLAW_DMG ),
CSW( CSW_ABUILDER_ALT,  "Granger Spit",    ABUILDER_BLOB_DMG ),
CSW( CSW_LEVEL1,        "Basilisk",        LEVEL1_CLAW_DMG ),
CSW( CSW_LEVEL2,        "Marauder",        LEVEL2_CLAW_DMG ),
CSW( CSW_LEVEL2_UPG,    "Adv. Marauder",   LEVEL2_CLAW_UPG_DMG ),
CSW( CSW_LEVEL2_ALT,    "Marauder Zap",    LEVEL2_AREAZAP_DMG ),
CSW( CSW_LEVEL3,        "Dragoon",         LEVEL3_CLAW_DMG ),
CSW( CSW_LEVEL3_ALT,    "Dragoon Barb",    LEVEL3_BOUNCEBALL_DMG ),
CSW( CSW_LEVEL4,        "Tyrant",          LEVEL4_CLAW_DMG ),
CSW( CSW_LEVEL4_ALT,    "Tyrant Flames",   50 ),
CSW( CSW_LEVEL5,        "Hummel",          LEVEL5_CLAW_DMG ),
CSW( CSW_LEVEL5_ALT,    "Hummel Prickles", LEVEL5_PRICKLES_DMG )

#define CSW_MAX_NAME_LEN 15
